### ISSUE TITLE
Installation of Python packages fails for AiiDA

### ISSUE THREAD

**Issue by blokhin** [basf/metis-backend#3]
```
root@metis-dev-backend:/data/metis-backend# pip install -r requirements.txt
...
Collecting git+https://github.com/tilde-lab/aiida-dummy (from -r requirements.txt (line 23))
  Cloning https://github.com/tilde-lab/aiida-dummy to /tmp/pip-req-build-3517oe95
  Running command git clone -q https://github.com/tilde-lab/aiida-dummy /tmp/pip-req-build-3517oe95
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-3517oe95/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-3517oe95/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_sh11pmp                                                                                                                                                                            
         cwd: /tmp/pip-req-build-3517oe95/                                                                                                                                                    
    Complete output (7 lines):                                                                                                                                                                
    Traceback (most recent call last):                                                                                                                                                        
      File "<string>", line 1, in <module>                                                                                                                                                    
      File "/tmp/pip-req-build-3517oe95/setup.py", line 6, in <module>                                                                                                                        
        from aiida_dummy import __version__                                                                                                                                                   
      File "/tmp/pip-req-build-3517oe95/aiida_dummy/__init__.py", line 2, in <module>                                                                                                         
        from aiida.orm import Int, Code                                                                                                                                                       
    ModuleNotFoundError: No module named 'aiida'
```

**Comment by blokhin** [comment]
Resolved with manual `pip install aiida_core`
